# Generated by Django 2.1 on 2019-05-02 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20)),
                ('financial_year', models.CharField(max_length=10, null=True)),
                ('receipt_no', models.CharField(max_length=50, null=True)),
                ('purchase_method', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_on', models.CharField(blank=True, max_length=20, null=True)),
                ('estimated_delivery_time', models.CharField(blank=True, max_length=40, null=True)),
                ('offer_id', models.IntegerField(blank=True, default=False, null=True)),
                ('points', models.DecimalField(decimal_places=2, max_digits=7)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=7)),
                ('packaging_charges', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payable_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('earn_points', models.DecimalField(decimal_places=2, max_digits=7)),
                ('special_note', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('order_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order_status', models.IntegerField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('offer_id', models.IntegerField()),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.IntegerField(default=False)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlogs', related_query_name='orderlog', to='orders.Order')),
            ],
            options={
                'db_table': 'order_logs',
            },
        ),
    ]
