# Generated by Django 2.1 on 2019-06-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_boy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='order',
            name='packaging_charges',
        ),
    ]
