# Generated by Django 2.1 on 2019-07-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_total_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
