# Generated by Django 2.1 on 2019-08-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_total_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='order',
            name='packaging_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
