# Generated by Django 2.1 on 2019-09-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchase_method',
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
