# Generated by Django 2.1 on 2019-05-29 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_promos',
            },
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='userpromocode',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_promo', related_query_name='user_promos', to='discounts.PromoCode'),
        ),
        migrations.AddField(
            model_name='userpromocode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo', related_query_name='promos', to=settings.AUTH_USER_MODEL),
        ),
    ]
