# Generated by Django 2.1 on 2019-05-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20190529_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
