# Generated by Django 2.1 on 2019-06-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_promocodeattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
