# Generated by Django 2.1 on 2019-06-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_auto_20190618_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
