# Generated by Django 2.1 on 2019-06-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_promocode_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='max_discount',
            new_name='percentage',
        ),
    ]
