# Generated by Django 2.1 on 2019-05-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20190502_0621'),
        ('common', '0002_auto_20190502_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promobanner',
            name='store',
        ),
        migrations.AddField(
            model_name='promobanner',
            name='kitchen',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.Kitchen'),
        ),
    ]
