# Generated by Django 2.1 on 2019-06-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190502_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='mobile_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
