# Generated by Django 2.1 on 2019-06-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190606_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='email',
        ),
        migrations.RemoveField(
            model_name='page',
            name='mobile_number',
        ),
    ]
