# Generated by Django 2.1 on 2019-05-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
