# Generated by Django 2.1 on 2019-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
