# Generated by Django 2.1 on 2019-06-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_verifyotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='save_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
