# Generated by Django 2.1 on 2019-06-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_address_save_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='land_mark',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
