# Generated by Django 2.1 on 2019-09-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_paymentmodel_card_holder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
