# Generated by Django 2.1 on 2019-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='BANKTXNID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='TXNID',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
