# Generated by Django 2.1 on 2019-05-02 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfeedback',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderfeedback',
            name='order',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='kitchenfeedback',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kitchenfeedback',
            name='kitchen',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kitchenfeedbacks', related_query_name='kitchenfeedback', to='stores.Kitchen'),
        ),
        migrations.AlterUniqueTogether(
            name='kitchenfeedback',
            unique_together={('kitchen', 'created_by')},
        ),
    ]
