# Generated by Django 2.1 on 2019-05-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20190502_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenfeedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
