# Generated by Django 2.1 on 2019-05-14 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_auto_20190502_0621'),
        ('feedback', '0003_kitchenfeedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=0)),
                ('created_on', models.DateTimeField(null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemfeedbacks', related_query_name='itemfeedback', to='feedback.OrderFeedback')),
                ('item', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemratings', related_query_name='itemrating', to='stores.Item')),
            ],
            options={
                'db_table': 'item_feedbacks',
            },
        ),
    ]
