# Generated by Django 2.1 on 2019-07-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_itemfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenfeedback',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
