# Generated by Django 2.1 on 2019-05-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20190515_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cost_for_two',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='minimum_order',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
