# Generated by Django 2.1 on 2019-05-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20190516_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='status',
            field=models.BooleanField(default=True, verbose_name='is_open'),
        ),
    ]
