# Generated by Django 2.1 on 2019-07-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_kitchen_packing_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
