# Generated by Django 2.1 on 2019-07-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_auto_20190720_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='logo_thumb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_thumb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
