# Generated by Django 2.1 on 2019-09-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20190722_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemanager',
            name='manager_p',
            field=models.CharField(blank=True, default='cft@12345', max_length=32),
        ),
    ]
