# Generated by Django 2.1 on 2019-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20190722_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
