# Generated by Django 2.1 on 2019-09-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_kitchen_short_name'),
        ('stores', '0013_storemanager_manager_p'),
    ]

    operations = [
    ]
