# Generated by Django 2.1 on 2019-09-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_merge_20190906_0727'),
        ('stores', '0015_merge_20190906_0831'),
    ]

    operations = [
    ]
