# Generated by Django 2.1 on 2019-09-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_merge_20190906_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='cod_limit',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
