# Generated by Django 2.1 on 2019-09-18 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0017_kitchen_cod_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_p', models.CharField(blank=True, default='cft@12345', max_length=32)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', related_query_name='manager', to='stores.Kitchen')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kitchen_managers',
            },
        ),
    ]
