# Generated by Django 2.1 on 2019-09-25 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_kitchendelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchendelivery',
            name='deliver_boy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
