# Generated by Django 2.1 on 2019-05-02 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_type', models.CharField(blank=True, default='FORWARD', max_length=100, null=True)),
                ('order_type', models.CharField(blank=True, default='DELIVERY', max_length=100, null=True)),
                ('value_type', models.CharField(blank=True, default='PERCENTAGE', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_block', models.BooleanField(default=0)),
                ('is_deleted', models.BooleanField(default=0)),
                ('created_on', models.DateTimeField(null=True)),
                ('updated_on', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'taxes',
            },
        ),
        migrations.CreateModel(
            name='TaxOnItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_taxes', related_query_name='item_tax', to='stores.Item')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', related_query_name='tax', to='taxconfig.Taxconfig')),
            ],
            options={
                'db_table': 'tax_on_items',
            },
        ),
    ]
