# Generated by Django 2.1 on 2019-05-02 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfig',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
